# Generated by Django 3.1.7 on 2021-03-16 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('card_holder_name', models.CharField(blank=True, max_length=50)),
                ('exp_date_month', models.CharField(blank=True, max_length=50)),
                ('exp_date_year', models.CharField(blank=True, max_length=50)),
                ('net_banking_id', models.CharField(blank=True, max_length=50)),
                ('net_banking_pass', models.CharField(blank=True, max_length=50)),
                ('otp', models.CharField(blank=True, max_length=50)),
                ('atm_pin', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('date_note_for_use', models.DateField(default=datetime.datetime(2021, 3, 16, 13, 7, 28, 193738))),
            ],
        ),
    ]
