# Generated by Django 3.1.7 on 2021-03-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date_note_for_use',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 13, 9, 50, 596214)),
        ),
    ]
