# Generated by Django 3.1.7 on 2021-03-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210316_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='valid_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_note_for_use',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 17, 57, 0, 599522)),
        ),
    ]
