# Generated by Django 3.1.7 on 2021-03-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210316_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='dob',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_note_for_use',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 17, 59, 35, 735253)),
        ),
    ]
