# Generated by Django 3.1.7 on 2021-03-16 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210316_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='net_banking_pass',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_note_for_use',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 18, 27, 28, 819386)),
        ),
    ]
