# Generated by Django 3.1.7 on 2021-03-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210316_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='date_note_for_use',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 18, 30, 4, 126117)),
        ),
    ]
