# Generated by Django 3.1.7 on 2021-03-17 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210316_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='exp_date_month',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='exp_date_year',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='exp_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 5, 30, 51, 902269)),
        ),
    ]
