# Generated by Django 3.1.7 on 2021-03-17 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210317_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 10, 44, 39, 961883)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='sNo',
            field=models.IntegerField(blank=True),
        ),
    ]
