# Generated by Django 3.1.7 on 2021-03-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210317_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 10, 50, 23, 912922)),
        ),
    ]
